spring.application.name=journal

# Database Settings
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Settings
app.security.secret-key=${SECRET_KEY}
app.security.access-token-expire=${ACCESS_TOKEN_EXPIRE}
app.security.refresh-token-expire=${REFRESH_TOKEN_EXPIRE}
